version: '3.3'

services:
  envoy:
    build:
      context: ./
      dockerfile: ./envoy.Dockerfile
    image: 'grpcweb:envoy'
    container_name: 'envoy'
    restart: always
    ports:
      - '8080:8080'
      - '9901:9901'
    command: ['/etc/envoy/envoy.yaml']
# TODO(youngteac.hong): We need to create Metis here
#    depends_on:
#      - metis
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
#    restart: always
    ports:
      - '27017:27017'